### ISSUE TITLE
명령어 및 입력인자 관련 질문

### ISSUE THREAD

**Issue by Nagnero** [Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3#1]
안녕하세요 컴퓨터정보공학부 22학번 연선우입니다.
3차 프로젝트 관련해서 질문이 있습니다.

1. "명령어의 인자는 공백으로 구분한다"고 나와있는데, 공백이 여러 개인 경우는 상정하지 않아도 되는지 궁금합니다.
예를 들어 "LOAD   graph_L.txt"처럼 LOAD 명령어 뒤에 공백이 3개인 경우도 고려해야 할까요?

2. 그래프 정보의 종류를 텍스트파일명으로 구분하는데, 첫번째 줄에 형식 정보 L이나 M을 다시 한번 받는 이유가 무엇인지 궁금합니다.
추가로 graph_L을 입력 받았는데, 첫째 줄에 M이 입력된 경우는 오류코드를 출력해야 할까요?

감사합니다.

**Comment by Jiseok-Yang** [comment]
안녕하세요

1. 공백 하나로만 구분할 예정입니다. LOAD" "graph_L.txt <= 이런 형식으로 모든 명령어의 공백은 1개만 들어갑니다. 

2. 해당 txt파일을 읽고 어떤 Class를 이용하여 그래프를 구축할지 결정해주기 위해 L, M 인자를 사용했습니다. 말씀하신 것처럼 파일명만 알아도 그래프 클래스를 고르는데 문제가 없지만, 이번 과제에서는 L, M을 이용하여 사용할 그래프 클래스를 선택해주시면 되겠습니다. 

3. 추가 질문 사항 graph_L.txt 인데 M을 주지 않을 거에요. 이렇게 소소한 에러 코드까지 잡아내고자 하는 게 과제의 목표는 아니라서 graph_L이면 L이 들어가있고 graph_M.txt면 M이 적혀있습니다.

혹시 설명이 부족했던 부분이 있다면 다시 질문 주시면 감사하겠습니다. 
감사합니다.

**Comment by Nagnero** [comment]
휴일에 빠른 답변 감사합니다!
