### ISSUE TITLE
가중치 범위 관련 질문

### ISSUE THREAD

**Issue by codml** [Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3#10]
Dijkstra, Bellman-Ford, Floyd를 구현할 때, 연결되어 있지 않은 간선의 가중치를 '매우 큰 수'로 생각해야 하는데, 테스트 케이스에서 주어질 가중치의 크기를 가늠할 수 없으니 이를 얼마로 설정해야 할 지 확신이 들지 않습니다. 혹시 테스트 케이스에서 주어지는 가중치가 '매우 큰 수'와 더해질 때 오버플로우가 절대 나지 않을 정도로 범위가 크지 않은지, 아니면 거의 모든 int 범위를 테스트해 오버플로우에 대한 예외처리도 고려해야 하는지 궁금합니다!

**Comment by YunatePark** [comment]
보통 inf로 사용하는데, 예를 들면 저 같은 경우에는 99999999정도 값으로 사용합니다.
