### ISSUE TITLE
Dijkstra 음수 가중치 예외처리에 관한 질문입니다. 

### ISSUE THREAD

**Issue by zzz332choi** [Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3#11]
안녕하세요. 컴퓨터정보공학부 2022202064 최봉규입니다. 

만약 그래프 상에서 음수의 가중치를 갖지만, Dijkstra를 시행했을 때, 해당 edge를 거쳐가지 않는다면 해당 케이스를 오류로 봐야할까요?

예를 든다면, 방향성을 갖는 그래프를 찾는다고 가정하겠습니다. out-degree만 있는 노드에 대해 음수의 가중치인 edge가 있습니다. startvertex를 다른 노드로 지정했을 때, 이 out-degree만 갖는 노드를 방문할 경우의 수는 0입니다. 이 경우, Dijkstra 그래프를 만드는 동안 음수의 edge를 거쳐가는 경우가 없는데, 해당 케이스 역시 에러로 보아야 하는가에 대해 궁금합니다. 

감사합니다.

**Comment by Jiseok-Yang** [comment]
네 이 케이스 같은 경우 오류로 보시면 될 거 같습니다.
