### ISSUE TITLE
클래스 멤버 변수 관련 질문

### ISSUE THREAD

**Issue by Chunsaeng20** [Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3#12]
안녕하세요 저는 [데이터구조설계 - 최상호 교수]를 수강하는 2020202082 정해성입니다.

ListGraph.h 파일을 보면 멤버 변수로 vector<int>* kw_graph 가 존재하는데 다른 어떤 함수도 인자나 반환형으로 vector를 가지지 않고, MatrixGraph.h 파일에는 존재하지 않는데 이는 어디에 사용하는 것인지 궁금합니다.

감사합니다.

**Comment by YunatePark** [comment]
KWANGWOON 탐색할 때 사용합니다. KW탐색이 아니면 해당 vector를 사용할 일이 전혀 없기 때문에 스켈레톤 코드에서 인자로 주어지지 않은거에요. 따라서 직접 함수 만드셔서 인자로 추가해서 사용하시면 됩니다.
