### ISSUE TITLE
txt파일 입력과 관련된 질문

### ISSUE THREAD

**Issue by hdh3665** [Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3#13]
안녕하십니까 데구설 이기훈교수님 분반, 데구실 월요일 분반 강의를 수강중인 2022202076 홍동현입니다. 

지난 2차 프로젝트와 관련하여 txt파일 입력에서 개행을 하였을 때 \r\n과 \n 의 차이로 프로그램이 실행되지 않아 이슈가 있었는데요,
3차 프로젝트 명세서를 읽어봐도 해당 내용과 관련해서 txt파일을 어떻게 처리하는지에 대한 내용이 적혀있지 않아 질문 남깁니다.

우분투 환경에서 txt파일을 생성해서 우분투 내에서 수정을 해도 되는지, 윈도우 환경에서 모든 내용을 작성해서 드래그 앤 드롭의 형태로 우분투 프로젝트 폴더 내에 넣은 후 실행을 해야하는지 궁금합니다. 감사합니다.

**Comment by YunatePark** [comment]
입력 데이터는 모두 우분투 환경에서 제작합니다.
