### ISSUE TITLE
Kwangwoon 알고리즘 및 함수 관련 질문 3가지

### ISSUE THREAD

**Issue by codml** [Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3#14]
안녕하세요, 실습 수요일 분반 2020202034 김태완입니다. Kwangwoon 알고리즘과 함수에 대해 질문이 몇 가지 생겨 문의드립니다.
1. 스켈레톤 코드 상에서 KWANGWOON 함수는 vertex라는 매개변수를 가지는데, 이는 무엇을 의미하는 것이라고 봐야 할까요? 탐색의 시작점이라고 생각했으나, KWANGWOON 알고리즘은 탐색을 항상 1부터 시작하는데, 시작점이 아니라면 어떤 의미인지 잘 모르겠습니다.
2. DS_Project3 5 page 에서KWANGWOON 알고리즘의 설명이 나와 있는데, 여기서 '그래프에 1번 정점이 없다면 에러를 출력한다'는 내용이 나와있는데, 그래프에 1번 정점이 없는 경우도 있나요? 2 page의 설명을 보면 '그래프의 모든 vertex의 값은 1 이상의 정수이며, 1부터 시작하여 1,2,3,4,... 순으로 정해진다고 가정한다'는 내용이 있어 그래프에 1번 정점이 없다는 말은 그래프가 비었다는 말로 밖에 해석이 되지 않아 문의드립니다.
3. Kwangwoon 알고리즘은 List graph의 데이터만 사용한다고 되어있는데, 그렇다면 가장 최근에 LOAD한 데이터가 matrix graph라면 에러코드를 출력해 주어야 하는 건가요?
감사합니다.

**Comment by YunatePark** [comment]
1. 시작점 맞습니다. 그냥 계속 1로 고정시켜서 주셔도 되고, 인자 없애셔도 됩니다.
2. 오류가 있었네요..네 맞습니다 그래프 정점은 1번부터 주어질거라 1번 정점이 없어서 에러가 출력되는 일은 없습니다. 무시하시면 될거 같아요.
3. 네 맞습니다
