### ISSUE TITLE
BFS, DFS 가중치 고려 문의

### ISSUE THREAD

**Issue by SeoeunY** [Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3#15]
프로젝트 제안서에 보면 BFS, DFS의 경우 방향성과 가중치를 고려한다고 적혀있는데
가중치를 고려한다면 접근 가능한 vertex의 가중치를 고려하여 순서대로 탐색해야 되는 건가요?
제가 알기로 BFS, DFS의 경우 가중치를 고려하지 않는 탐색 방법으로 알고 있는데 답변 부탁드립니다.
감사합니다.

**Comment by YunatePark** [comment]
아 오타입니다..죄송합니다 가중치는 고려하지 않습니다
