### ISSUE TITLE
크루스칼 정렬 관련 문의

### ISSUE THREAD

**Issue by SeoeunY** [Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3#16]
연결선을 정렬할 때 sorting 알고리즘을 사용한다고 적혀있는데 혹시 map을 사용하거나 다른 방법을 사용해 정렬해도 될까요?

**Comment by YunatePark** [comment]
크루스칼에서 사용되는 정렬 알고리즘은 제안서에 적혀있는 퀵소트를 구현하셔서 사용하시면 됩니다

**Comment by SeoeunY** [comment]
퀵소트 사용하지 않고 멀티맵의 키 캆으로 가중치를 저장하는 형식은 안될까요?ㅜㅜ
