### ISSUE TITLE
그래프 입력 관련 질문 있습니다.

### ISSUE THREAD

**Issue by evejaeyong** [Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3#17]
안녕하세요. 데이터구조 과목을 수강하는 2022202088 김재용입니다.

LOAD 명령어를 통해 그래프 입력을 받을 때, 양 방향으로 연결된 케이스가 입력으로 들어가는지 궁금합니다.
예를 들어 node 1-> node 2로 이동하는 간선이 존재하는데, node 2-> node 1로 이동하는 가중치가 다른 간선이 존재할 수 있는지 궁금합니다.

감사합니다.

**Comment by YunatePark** [comment]
네 존재합니다. 그리고 해당 입력 데이터의 경우 무방향으로 간주될 수 없기 때문에(가중치 두개 중 하나 포기해야하는 조건을 따로 제시하지 않음) 해당 데이터는 oprtion으로 Y만 주어서 테스트 할 예정입니다
