### ISSUE TITLE
edge 관련 질문입니다

### ISSUE THREAD

**Issue by lovejg** [Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3#18]
2020202068 컴퓨터정보공학부 박찬영입니다
제가 데구설 강의에서 듣기로는 graph에서 (u,v) 혹은 <u,v>에서 u!=v가 전제 조건이고, 그래서 matrix로 표현했을 때 diagonal이 모두 0인 것으로 알고 있는데, (u,u)와 같은 자기자신을 갖는 경우도 예외처리를 모두 해줘야 하나요?
항상 고생 많으십니다!

**Comment by Jiseok-Yang** [comment]
이론 상 자기 자신을 갖는 경우는 없기 떄문에 그렇게 처리해주시면 될 거 같습니다.
