### ISSUE TITLE
광운 search 관련 질문입니다. 

### ISSUE THREAD

**Issue by jcg100** [Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3#19]
"정점 1 부터 탐색을 시작하여 탐색의 순서를 출력하면 된다. 현재 연결되어 있는 간선의 수가 짝수라면 가장 작은 정점 번호로 방문을 시작하고, 홀수라면 가장 큰 정점의 번호로 방문하도록 한다."

 이 방법을 사용하면 특정 정점에 연결되어 있는 간선이 하나 인 경우 혹은 1번 정점과 연결된 간선이 없는 경우 해당 정점에 도착하면 그래프 전체의 정점를 탐색하지 못하였어도 탐색이 종료되는 것으로 생각되는데 맞는 것인지 궁금합니다.

**Comment by Jiseok-Yang** [comment]
네 맞습니다. 그래프 전체 정점을 탐색하지 못해도 탐색이 종료되는 것이 맞습니다.
