### ISSUE TITLE
그래프 구축 및 명령어 오류 처리 관련 질문입니다.

### ISSUE THREAD

**Issue by ChoiEunchan** [Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3#2]
혹시 그래프를 생성할 때 그래프 노드 수와는 별개로 vertex number가 graph size보다 큰 경우도 있을까요?
그리고 제안서에 각 명령어들의 오류 출력 조건을 보면 vertex를 쓰지 않은 경우에 각 command에 해당하는
오류 코드를 쓰라고 나와 있는데, 이 부분을 명령어 오류로 처리해도 될까요?
예를 들어 BFS를 동작할 때는 방향성과 시작 vertex 번호를 쓰게 나와 있는데, 만약 여기서 vertex번호를 쓰지 않은 경우에
제안서에서는 BFS의 오류 코드인 300을 출력하라고 나와있습니다. 질문 드리고 싶은 것은 오류 코드를 300이 아닌
명령어 오류 코드인 1000을 출력하도록 해도 되는지 여쭤보고 싶습니다.
위 사례 이외의 명령어 오류를 처리할 때도 각 명령어 별 오류 코드(100 ~ 900)로 출력하는 것이 아닌
잘못된 명령어 오류 코드(1000)로 출력해도 되는지도 여쭤봅니다.

**Comment by Jiseok-Yang** [comment]
안녕하세요. 

vertex number가 graph size보다 큰 경우는 없을 거 같습니다. 

또한 명령어 코드는 명령어 별 오류 코드인 (100~900)으로만 처리해주실 바랍니다.

임의의 명령어 오류코드(1000)으로 출력하고 싶은 이유에 대해서 혹시 여쭤봐도 될까요??

**Comment by ChoiEunchan** [comment]
성능 상 저렇게 하는게 효율이 좋을 것 같아서 여쭤봤습니다.
