### ISSUE TITLE
LOAD 명령어 관련 질문

### ISSUE THREAD

**Issue by dbfanck** [Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3#21]
안녕하세요 컴퓨터정보공학부 2022202012 손민입니다.

프로젝트 문서에서
"기존에 그래프 정보가 존재할 때 LOAD 가 입력되면 기존 그래프 정보는 삭제하고 새로 그래프를 생성한다"고 되어 있는데,

만약 예외처리를 해야하는 경우(텍스트 파일이 존재하지 않거나, 비어 있는 경우 등)에 기존 그래프 정보가 존재한다면
해당 경우에도 기존 그래프 정보를 삭제해야하는지, 아니면 기존 그래프 정보를 유지해야하는지 궁금합니다.

감사합니다.

**Comment by Jiseok-Yang** [comment]
데이터 텍스트 파일은 무조건 있을 예정이라 명령어 텍스트 파일의 경우에만 오류 처리 해주시면 될 거 같아요

**Comment by dbfanck** [comment]
그럼 기존 그래프 정보가 존재할 때 LOAD 입력 시 기존 그래프는 무조건 삭제하는 걸로 이해하면 될까요?

**Comment by YunatePark** [comment]
네네 맞습니다 제안서에 적혀있는대로 구현하시면 됩니다
