### ISSUE TITLE
그래프 방향성 무방향성 관련 질문입니다.

### ISSUE THREAD

**Issue by kindYeom** [Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3#22]
안녕하세요 컴퓨터정보공학부 2020202037 염정호 입니다.
그래프 관련해서 질문드립니다.
무방향성 그래프의 경우 행렬이 대칭구조를 갖게 되는데 그래프에서 무방향성으로 테스트 하실 때 대칭구조로 된 행렬이 주어지는 건가요??

**Comment by YunatePark** [comment]
아닙니다. 방향성이 있는 데이터가 주어질 경우, 방향성이 있는 데이터로 구축된 그래프를 양방향으로 만들어주시고 그래프 탐색을 시작하면 됩니다.
