### ISSUE TITLE
BELLMANFORD 알고리즘 ERROR 우선순위 관련

### ISSUE THREAD

**Issue by Pasame** [Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3#23]
안녕하세요 2022202073 컴퓨터정보공학부 박현웅입니다.
![image](https://github.com/Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3/assets/70192511/3b7487de-5e83-4755-a37f-f36796d51515)
Bellman-Ford 알고리즘에서 음수 사이클이 발생한다면 위의 사진에 나온 설명과 같이 error를 출력해야 하며, startvertex에서 endvertex까지 연결이 되지 않을 때 X를 출력하여야 한다고 기술되어 있는데, 
![image](https://github.com/Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3/assets/70192511/b8381612-4a59-4b95-ba83-3255fceb3d94)

위 사진과 같이 1-7이 연결된 그래프, 8-12가 연결된 그래프 두 가지의 작은 그래프로 이루어진 데이터 상황에서 8~12graph에서 음수 사이클이 발생한다고 할 때

1. BELLMANFORD 알고리즘을 통해서 1->8의 경로를 탐색한다고 하면 서로 분리된 상황이므로 경로가 없지만 음수 사이클이 있으므로 ERROR를 출력 해야 하는지 아니면 X를 출력해야 하는지
2. BELLMANFORD 알고리즘을 통해서 1->7의 경로를 확인하는데 1-7에서는 음수 사이클이 발생하지 않으나 8-12에서 음수 사이클이 발생하므로 음수 사이클을 탐색을 하지 않아도 ERROR를 출력해야 하는지 아니면 경로를 출력해야 하는지

에 대한 궁금증이 생겨 질문 드렸습니다. 

_(2023-12-13 23:58 그래프 사진 첨부로 수정)_

**Comment by YunatePark** [comment]
1번의 경우 x를 출력해주시면 됩니다
2번의 경우 경로를 출력해주시면 됩니다
