### ISSUE TITLE
다익스트라 예시 관련 질문

### ISSUE THREAD

**Issue by vamosdancar** [Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3#24]
제안서에서 DIJKSTRA N 5를 입력하면

========= Dijkstra =========
Undirected Graph Dijkstra result
startvertex: 1
[2] 1-> 2 (6)
[3] 1 -> 3 (2)
[4] 1 -> 3 -> 5 -> 4 (7)
[5] 1 -> 3 -> 5 (5)
[6] 1 -> 3 -> 6 (10)
[7] 1 -> 3 -> 5 -> 4 -> 7 (10)
==========================
이렇게 출력된다고 명시되어 있는데, 
vertex가 5부터 시작해서 결과를 출력하는 것이 아닌가요? start vertex와 별개인지 궁금합니다.

**Comment by YunatePark** [comment]
아 오타를 잡아낸다고 한게 오타입니다.. 죄송합니다
