### ISSUE TITLE
Graph 소스 함수 질문

### ISSUE THREAD

**Issue by babydragon0073** [Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3#3]
그래프에서 getAdjacentEdges함수와 getAdjacentEdgesDirect함수로 나누어져 있는데 굳이 나누어서 쓰는 이유를 모르겠습니다

제가 생각했을 때 vertex가 주어지면 그 vertex의 인접 edge들을 구하는 함수니까
 그 vertex에 있는 것들만 한번 비교하고 찾으면 방향성이 있든 없든 같은 코드로 구할 수 있다고 생각이 되는데 
제가 어떤 부분을 잘못 생각한걸까요?

**Comment by Jiseok-Yang** [comment]
안녕하세요.

우선 말씀해주신 것 중 잘못된 것은 없다고 생각됩니다.

getAdjacentEdges함수만 쓰시고 구현하실 수 있으시면 그렇게 구현해보시면 될 거 같습니다.

감사합니다.
