### ISSUE TITLE
LOAD 명령어 질문

### ISSUE THREAD

**Issue by zzz332choi** [Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3#4]
안녕하세요. 컴퓨터정보공학부 2022202064 최봉규입니다.
LOAD 명령어에 대해 질문이 있습니다. 

명령어 사용 예 및 기능표에 LOAD 명령어는 "텍스트 파일이 존재하지 않거나, 비어 있는 경우, 출력 파일(log.txt)에 오류 코드(100)을 출력한다. "라고 되어있습니다. 
여기서 비어 있는 경우라고 하면, 

1. [textfile]을 써야 되는 란에 쓰이지 않은 경우인 커맨드가 LOAD이고 뒤에 아무 것도 존재하지 않는 경우로 즉, 인자가 부족한 경우
2. 인자가 부족하진 않으나, 해당 파일 안에 내용이 없는 경우

이 두 개의 케이스중 무엇을 가리키는지 궁금합니다.

**Comment by Jiseok-Yang** [comment]
안녕하세요.

말씀해주신 1,2 내용 모두 해당된다고 생각해주시면 될 거 같습니다.

감사합니다.
