### ISSUE TITLE
과제 pdf 10page print format 관련 질문

### ISSUE THREAD

**Issue by codml** [Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3#5]
10page에 print format 중 BFS, DFS 출력 예시에서 질문이 생겨 문의드립니다.
예시에는 BFS는 1->2->3->4->5->6, DFS는 1->2->4->3->6->5로 1~6번 vertex만 경로에 포함되어 있는데
7번 vertex도 Directed로 하든 UnDirected로 하든 방문할 수 있지 않나요?
오타인지 아니면 제가 BFS, DFS에 대한 이해가 부족한 것인지 궁금합니다!

**Comment by YunatePark** [comment]
아하 해당 부분은 단순 예시라서 제안서에 적혀있는 그래프 데이터와는 상관없습니다!
