### ISSUE TITLE
DFS, BFS 시작 Vertex 관련 질문

### ISSUE THREAD

**Issue by jonyeoke** [Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3#7]
![image](https://github.com/Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3/assets/144398689/66bead64-6030-4de5-8dd3-4572cf5536c4)
안녕하세요, 컴퓨터정보공학부 2020202054 이종혁입니다.

다름이 아니라 이번 과제에서 Vertex가 1부터 시작되는 것으로 알고 있고, 다른 Method들은 모두 1부터 시작하는 예시로 나와있습니다.

혹시 DFS랑 BFS가 0부터 시작되는 것으로 예시를 든 것이 잘못 나온 것인가요, 아님 다른 뜻이 있으신건가요?

감사합니다.

**Comment by YunatePark** [comment]
단순 예시라 그냥 의미 없이 적어둔 것입니다. 1번부터 시작이라 최소 1부터 시작합니다
