### ISSUE TITLE
함수 인자 변경 관련 질문

### ISSUE THREAD

**Issue by codml** [Jiseok-Yang/2023_Kwangwoon_Univ_CE_DS_Project_3#9]
스켈레톤 코드에 제시된 함수들에 인자를 임의로 추가해도 되나요?
예를 들어 BFS, DFS 등의 함수에 ofstream *fout은 출력을 위해 꼭 필요할 거 같아 문의드립니다!
추가로 위 사항이 가능하다면, getAdjacentEdges 함수에 char option을 인자로 추가해 Directed, Undirected일 때 둘 다 사용 가능하도록 수정도 가능한 건가요?

**Comment by YunatePark** [comment]
네 말씀드린 것처럼 인자 추가 가능합니다. 
근데 사실 현재 스켈레톤 코드상으로도 log.txt에 결과를 작성하는데 문제 없습니다...! 추가적인 인자 없이도 구현 가능합니다. 하지만 이를 파악하기 어려우시다면 인자 추가하셔도 됩니다. 그리고 getAdjacentEdges함수는 제가 일부러 스켈레톤 코드로 두가지로 제공해 드렸는데 굳이 option을 받아서 동작할 필요는 없어 보이기는 합니다. .!
